name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          cd /home/runner/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > id_rsa  # Remove carriage returns
          sudo chmod 600 id_rsa  # Set correct permissions
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts  # Add host key

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ secrets.ANSIBLE_HOST }}, -u ${{ secrets.ANSIBLE_USER }} playbook.yml
