name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa  # Remove carriage returns
          chmod 600 ~/.ssh/id_rsa  # Set correct permissions
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts  # Add host key
          ssh -T -i ~/.ssh/id_rsa ${{ secrets.ANSIBLE_USER }}@${{ secrets.ANSIBLE_HOST }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ secrets.ANSIBLE_HOST }}, -u ${{ secrets.ANSIBLE_USER }} playbook.yml

      - name: Transfer files to EC2
        run: |
         sudo scp -r -o StrictHostKeyChecking=no * ${{ secrets.AWS_EC2_USER }}@${{ secrets.ANSIBLE_HOST }}:/home/${{ secrets.ANSIBLE_USER }}/app/
